name: Workflow

on: push

jobs:
  ay7aga_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello World" 
      - run: echo "HERE AFTER HELLO"
      - uses: actions/checkout@v4
      - run: echo "Current github repo ${{ github.repository }}"
      - name: List repo files and directories
        run: echo "FILES AND REPOS ${{ github.workspace }}"